# needs
# 하나의 워크플로우에서 여러 개의 잡을 사용하는 경우가 많음
# job은 기본적으로 병렬로 실행되지만, needs 키워드를 사용하면 순차적으로 실행할 수 있음
# needs는 하나의 job이 다른 job 또는 여러 job이 완료될 때 실행되도록 할 때 사용
# 즉 여러 job의 실행 순서를 조절 가능
# 테스트 job이 실행되고, 그 job이 성공할 때 배포 job을 실행하도록 설정 가능

name: needs-workflow
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "job1 done"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: echo
        run: echo "job2 done"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: | # exit 1 =>  job3이 실패하도록 설정
          echo "job3 failed"
          exit 1
  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
      - name: echo
        run: echo "job4 done"
# job1과 job3은 병렬로 실행
# job1이 성공하면 job2가 실행되고, job3이 성공하면 job4가 실행됨
