# filter
# 이벤트가 특정 조건에 부합할 때 실행시킬 수 있음
# 특정 branch / path / tag에서 실행시킬 수 있음

name: branch-filter
on:
  push:
    branches: ["dev"]

jobs:
  branch-filter:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hello
