# secret
# 민감한 데이터를 안전하게 저장해서 워크플로우에서 사용할 수 있게 해주는 기능
# 사용 이유 : 민감한 정보를 코드와 분리하여 노출되는 것을 방지하기 위해 사용
# 주로 api key, 암호, 인증 토큰 같은 데이터를 저장

# 깃헙에서 안전하게 암호화하여 저장
# 로그에도 기록되지 않고 출력 시에 마스킹되어 출력됨
# 워크플로우 실행 중에만 접근할 수 있음

# 정의된 시크릿 값을 바꾸면 워크플로우 결과가 달라질 수 있음

name: secrets
on: push

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: get secrets
        run: echo ${{ secrets.level }}
