# CI/CD 시나리오 1
# 가정
# - dev 브랜치를 개발환경으로 사용할 떄, 개발 환경에만 배포하는 CI/CD를 구성
# branch
# - dev
# 요구사항
# - 특정 path에 대해서만 실행
# - dev branch로 PR이 생성 & 동기화될 때 테스트 작업 실행 (CI)
# - PR이 dev branch로 머지되면, 이미지 빌드하고 개발 환경에 배포 (CD)
# - 배포 성공 여부를 슬랙으로 전송

name: cicd-1
on:
  pull_request:
    types: [opened, synchronize, closed] # closed가 있어야 PR이 머지되었을 때 실행 가능
    branches: [dev]
    paths:
      - 'my-app/**'

jobs:
  test:
    if: github.event.action == 'opend' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  image-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: [image-deploy]
    steps:
      - name: checkout
        uses: actions/checkout@v4
