name: issue-workflow
on:
  issues:
    types: [opened] # 이슈가 생성될 때만 github action이 실행됨

jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github actions
